CREATE TYPE CLASS AS ENUM ('First', 'Second', 'Third');

CREATE CAST (VARCHAR AS CLASS) WITH INOUT AS IMPLICIT;

CREATE TABLE passengers (
	id BIGSERIAL PRIMARY KEY,
	survived BOOLEAN NOT NULL,
	pclass CLASS NOT NULL,
	name VARCHAR(100) NOT NULL,
	sex VARCHAR(6) NOT NULL,
	age FLOAT NOT NULL,
	siblings_spouses SMALLINT NOT NULL,
	parents_children SMALLINT NOT NULL,
	fare DOUBLE PRECISION NOT NULL
);